Add missing includes to avoid warnings
In file included from gss-genr.c:45:
kex.h:173:32: warning: ‘struct sshkey’ declared inside parameter list will not be visible outside of this definition or declaration
  int (*verify_host_key)(struct sshkey *, struct ssh *);
                                ^~~~~~
gss-genr.c: In function ‘ssh_gssapi_sshpkt_get_buffer_desc’:
gss-genr.c:95:11: warning: implicit declaration of function ‘sshpkt_get_string’; did you mean ‘sshbuf_get_string’? [-Wimplicit-function-declaration]
  if ((r = sshpkt_get_string(ssh, &p, &len)) != 0)
           ^~~~~~~~~~~~~~~~~
           sshbuf_get_string